version: 1.0.{build}
os: Visual Studio 2017
configuration: Release

pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
  - git config --global core.autocrlf input
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_TAG" -ne "true") { $env:VERSION_SUFFIX="pre" }
  - ps: 'Write-Output "Version: $($env:APPVEYOR_BUILD_VERSION)-$($env:VERSION_SUFFIX)"'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build -c Release

artifacts:
  - path: '**\*.nupkg'
    name: ReleaseArtifacts

deploy:
  - provider: NuGet
    on:
      appveyor_repo_tag: true
    api_key:
      secure: gKVQGHC6gF2JSdhVV8KcO9WNAPd0N9DnpUQBBTbCsdhRYZ5m+pp0jpbaPGEOhtU8
    artifact: /.*\.nupkg/