name: Release

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
    - name: Pack
      run: dotnet pack -c Release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: '**/*.nupkg'
        retention-days: 5
    - name: Publish
      run: dotnet nuget push src/Tcg.Owin.Security.OpenIdConnect/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      

